# Gruppo di host su cui verrà eseguito il playbook di deploy
[target]

# Ansible gira sulla vm: la porta 2210 inoltra le connessioni alla 22 del target
# "dind" è l'alias dell'host
dind ansible_host=127.0.0.1 ansible_port=2210 ansible_user=devops
