pipeline {
    agent any

    environment {
        REGISTRY = 'registry:5000'
        IMAGE    = 'webapp'
    }


// BUILD_NUMBER aumenta a ogni esecuzione di questo job
// Lo passa al Dockerfile per mostrarlo nella pagina web
// Assegna alla stessa immagine il tag numerico e il tag latest

    stages {
        stage('Build') {
            steps {
                sh """
                    docker build \
                      --build-arg BUILD_NUMBER=${env.BUILD_NUMBER} \
                      -t ${REGISTRY}/${IMAGE}:${env.BUILD_NUMBER} \
                      -t ${REGISTRY}/${IMAGE}:latest \
                      step5-jenkins/app
                """
            }
        }


// Pubblica entrambi i tag nel registry raggiungibile dal target

        stage('Push') {
            steps {
                sh """
                    docker push ${REGISTRY}/${IMAGE}:${env.BUILD_NUMBER}
                    docker push ${REGISTRY}/${IMAGE}:latest
                """
            }
        }


// Il plugin Ansible esegue il playbook sugli host dell'inventario
// Recupera la chiave SSH salvata delle credenziali Jenkins
// Passa ad Ansible il tag preciso della build appena pubblicata

        stage('Deploy') {
            steps {
                ansiblePlaybook(
                    playbook: 'step5-jenkins/deploy.yml',
                    inventory: 'step5-jenkins/inventory.ini',
                    credentialsId: 'dind-ssh-key',
                    hostKeyChecking: false,
                    extraVars: [build_number: "${env.BUILD_NUMBER}"]
                )
            }
        }
    }
}
