FROM docker.io/rockylinux/rockylinux:9

ARG SSH_USER=devops

RUN dnf -y update && \
    dnf -y install openssh-server sudo && \
    dnf clean all && rm -rf /var/cache/dnf

RUN ssh-keygen -A

RUN useradd --create-home --shell /bin/bash "${SSH_USER}" && \
    usermod -aG wheel "${SSH_USER}" && \
    echo "${SSH_USER} ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/90-${SSH_USER}" && \
    chmod 0440 "/etc/sudoers.d/90-${SSH_USER}"

COPY authorized_keys /tmp/authorized_keys
RUN install -d -m 0700 -o "${SSH_USER}" -g "${SSH_USER}" "/home/${SSH_USER}/.ssh" && \
    install -m 0600 -o "${SSH_USER}" -g "${SSH_USER}" \
	/tmp/authorized_keys "/home/${SSH_USER}/.ssh/authorized_keys" && \
    rm /tmp/authorized_keys

COPY sshd_hardening.conf /etc/ssh/sshd_config.d/10-formazione.conf

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D", "-e"]
